### ISSUE TITLE
Matte over blur issue in AE - look like "repeat edge pixels" is turned on

### ISSUE THREAD

**Issue by ravidsand** [airbnb/lottie-web#2102]
Hi All,

I've created an animation in AE and exported via Bodymovin.
All is fine, except for a shape that require both Gaussian blur and alpha matte.
the matte (either using set matte effect of Track Matte) works, but makes the Gaussian blur look "cut".
attached screenshot
![image](https://user-images.githubusercontent.com/44798736/79053015-d1564880-7c42-11ea-91c1-66c60dc2f2ab.png)

would appreciate any help solving this
thanks everyone!

**Comment by bodymovin** [comment]
hi, can you share the .aep?

**Comment by ravidsand** [comment]
> hi, can you share the .aep?

@bodymovin  sure, attached. thanks! 

[bodymovin test 1.aep.zip](https://github.com/airbnb/lottie-web/files/4468266/bodymovin.test.1.aep.zip)

**Comment by bodymovin** [comment]
[bodymovin test 1.zip](https://github.com/airbnb/lottie-web/files/4472422/bodymovin.test.1.zip)
Browsers are not good at measuring element sizes with filters applied, that's why the mask is not correctly measured.
I've added an extra group on your `r sh` layer called `Filler` which consists of a rectangle and a transparent fill that should fix the issue.

**Comment by ision-industries** [comment]
@bodymovin sorry for the super late reply but I am really confused at this point. I have read countless threads about mattes and mask issues, but your answer of "adding a rectangle with a transparent fill" has come up time and time again. Can you please clarify how a transparent shape fixes the matte mask issue? I have tried to do that but the alpha matte issue still persists, maybe I am doing it wrong. Do I add the rectangle to the layer that is using a track matte or should I add it to the matte layer? Do I add a new group with with the rectangle and transparent fill? This matte issue I am dealing with is driving me crazy. Please help me, I would like to figure out the problem causing the issue to fix it so I can publish these animations

**Comment by bodymovin** [comment]
@ision-industries in order to apply a mask, the svg engine from browsers calculate the bounding box of the masked element. But that calculation doesn't account for exceeding pixels of that bounding box. Usually, strokes and effects exceed the bounding box and that's the reason why they get clipped.
By adding an extra shape larger than the stroke or effects, it tricks the svg engine into believing that the bounding box is larger, so elements don't get clipped.
Adding a rectangle with a transparent fill is the quickest way to achieve this.
Hope this helps to clarify why this solves this type of problem.

**Comment by ision-industries** [comment]
@bodymovin thank you for delving in to how this stuff works. I just like having context of how things work. Does this transparent rectangle fix only work on layers with a mask? Does it work with layers using another layer as a track matte?

**Comment by bodymovin** [comment]
@ision-industries it should work with track matte layers too.

**Comment by ision-industries** [comment]
@bodymovin should I add the transparent filled shape to the the layer that is the track matte or the layer that is using the other layer as a track matte?

**Comment by bodymovin** [comment]
@ision-industries to the masked layer.

**Comment by johnamanathon** [comment]
I am having a similar issue here. Gaussian blur, mask applied, strange clipping and artifacting. Does anyone have a fix for this issue?

I attached the AE file.

[spinner-v2.aep.zip](https://github.com/user-attachments/files/20190109/spinner-v2.aep.zip)
